<h1>NumPy Basics: Arrays and Vectorized Computation</h1>

<h2>The NumPy ndarray: A Multidimensional Array Object</h2> 

In [1]:
import numpy as np

In [5]:
data = np.array([[0.9526, -0.246, -0.8856],
              [0.5639, 0.2379, 0.9104]])

In [6]:
data

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [7]:
data * 10

array([[ 9.526, -2.46 , -8.856],
       [ 5.639,  2.379,  9.104]])

In [8]:
data + data

array([[ 1.9052, -0.492 , -1.7712],
       [ 1.1278,  0.4758,  1.8208]])

In [13]:
wrong_array = np.array([[object(), 2], 
                       ['a', 'b']])

In [14]:
wrong_array # cast to object

array([[<object object at 0x000001DD7BBCAF10>, 2],
       ['a', 'b']], dtype=object)

In [15]:
data.shape

(2, 3)

In [16]:
data.dtype

dtype('float64')

In [17]:
wrong_array.dtype

dtype('O')

<h3>Creating ndarrays</h3>

In [19]:
data1 = [6, 7.5, 8, 0, 1]

In [20]:
arr1 = np.array(data1)

In [21]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [22]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [23]:
arr2 = np.array(data2)

In [24]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
arr2.ndim

2

In [26]:
arr2.shape

(2, 4)

In [27]:
arr1.dtype

dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

In [29]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [31]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [32]:
np.empty((2, 3, 2))  # not always returns zeros. it can return some garbage 

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [33]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
np.ones((2, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [36]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

<h3>Data Types for ndarrays</h3>

In [37]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [38]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [39]:
arr1.dtype

dtype('float64')

In [40]:
arr2.dtype

dtype('int32')

In [41]:
arr = np.array([1, 2, 3, 4, 5])

In [42]:
arr.dtype

dtype('int32')

In [43]:
float_arr = arr.astype(np.float64)

In [44]:
float_arr.dtype

dtype('float64')

In [45]:
float_arr

array([ 1.,  2.,  3.,  4.,  5.])

In [46]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [47]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [48]:
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [49]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [50]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [51]:
numeric_strings.astype(np.float64)

array([  1.25,  -9.6 ,  42.  ])

In [52]:
empty_uint32 = np.empty(8, dtype='u4')

In [53]:
empty_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

<h3>Operations between Arrays and Scalars</h3>

In [54]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [55]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [56]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [57]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [58]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [59]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

<h3>Basic Indexing and Slicing</h3>

In [60]:
arr = np.arange(10)

In [61]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr[5]

5

In [63]:
arr[5:8]

array([5, 6, 7])

In [64]:
arr[5:8] = 12

In [65]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [66]:
arr_slice = arr[5:8]

In [67]:
arr_slice[1] = 12345

In [68]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [69]:
arr_slice[:] = 64

In [70]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [71]:
slice_copy = arr_slice.copy()

In [72]:
slice_copy

array([64, 64, 64])

In [73]:
slice_copy[:] = 0

In [74]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [75]:
slice_copy

array([0, 0, 0])

In [76]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [77]:
arr2d[2]

array([7, 8, 9])

In [78]:
arr2d[0][2]

3

In [79]:
arr2d[0, 2] # the same as previous

3

In [80]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [81]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [82]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
old_values = arr3d[0].copy()

In [84]:
arr3d[0] = 53

In [85]:
arr3d

array([[[53, 53, 53],
        [53, 53, 53]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [86]:
arr3d[0] = old_values

In [87]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [88]:
arr3d[1, 0]

array([7, 8, 9])

In [89]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [90]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [91]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [94]:
arr2d[1, :2]

array([4, 5])

In [95]:
arr2d[2, :1]

array([7])

In [96]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [97]:
arr2d[:2, 1:] = 0

In [98]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [99]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [100]:
arr2d[2].shape

(3,)

In [101]:
arr2d[1].shape

(3,)

In [102]:
arr3d[1].shape

(2, 3)

In [106]:
arr3d[0].shape

(2, 3)

In [107]:
arr3d[0, 1:].shape

(1, 3)

In [108]:
arr3d[0, 1:]

array([[4, 5, 6]])

In [109]:
arr3d[0,1].shape

(3,)

In [110]:
arr3d[:1, 0].shape

(1, 3)

In [111]:
arr3d[0, 1]

array([4, 5, 6])

In [112]:
arr3d[0,0,0].shape

()

In [113]:
arr2d[1, :2].shape

(2,)

In [114]:
arr2d[1, :2]

array([4, 5])

In [115]:
arr2d[1, :1].shape

(1,)

<h3>Boolean Indexing</h3>

In [116]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [119]:
data = np.random.randn(7, 4)

In [120]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [121]:
data

array([[-0.5188232 ,  1.68205242, -0.91390822,  1.01310711],
       [-1.08737148,  1.56957886, -0.97882537,  1.1048224 ],
       [-0.59500475,  0.71531654,  0.84273568,  0.51857181],
       [-0.66601895, -0.3709413 , -2.17966666,  1.17710721],
       [-0.43184667,  0.24308224,  0.65241893,  0.0124309 ],
       [ 1.93979481,  2.15641302, -0.18164607,  0.95050426],
       [-1.56534225,  1.39883095,  0.26600091,  1.95348492]])

In [122]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [123]:
data[names == 'Bob']

array([[-0.5188232 ,  1.68205242, -0.91390822,  1.01310711],
       [-0.66601895, -0.3709413 , -2.17966666,  1.17710721]])

In [124]:
data[names == 'Bob', 2:]

array([[-0.91390822,  1.01310711],
       [-2.17966666,  1.17710721]])

In [125]:
data[names == 'Bob', 3]

array([ 1.01310711,  1.17710721])

In [130]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [132]:
data[(names != 'Bob')]

array([[-1.08737148,  1.56957886, -0.97882537,  1.1048224 ],
       [-0.59500475,  0.71531654,  0.84273568,  0.51857181],
       [-0.43184667,  0.24308224,  0.65241893,  0.0124309 ],
       [ 1.93979481,  2.15641302, -0.18164607,  0.95050426],
       [-1.56534225,  1.39883095,  0.26600091,  1.95348492]])

In [133]:
data[np.logical_not(names == 'Bob')]

array([[-1.08737148,  1.56957886, -0.97882537,  1.1048224 ],
       [-0.59500475,  0.71531654,  0.84273568,  0.51857181],
       [-0.43184667,  0.24308224,  0.65241893,  0.0124309 ],
       [ 1.93979481,  2.15641302, -0.18164607,  0.95050426],
       [-1.56534225,  1.39883095,  0.26600091,  1.95348492]])

In [134]:
data[np.invert(names == 'Bob')]

array([[-1.08737148,  1.56957886, -0.97882537,  1.1048224 ],
       [-0.59500475,  0.71531654,  0.84273568,  0.51857181],
       [-0.43184667,  0.24308224,  0.65241893,  0.0124309 ],
       [ 1.93979481,  2.15641302, -0.18164607,  0.95050426],
       [-1.56534225,  1.39883095,  0.26600091,  1.95348492]])

In [135]:
mask = (names == 'Bob') | (names == 'Will')

In [136]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [137]:
data[mask]

array([[-0.5188232 ,  1.68205242, -0.91390822,  1.01310711],
       [-0.59500475,  0.71531654,  0.84273568,  0.51857181],
       [-0.66601895, -0.3709413 , -2.17966666,  1.17710721],
       [-0.43184667,  0.24308224,  0.65241893,  0.0124309 ]])

In [143]:
# Selecting data from an array by boolean indexing always creates a copy of the data,
# even if the returned array is unchanged.
data_copy = data[mask]

In [144]:
data_copy

array([[-0.5188232 ,  1.68205242, -0.91390822,  1.01310711],
       [-0.59500475,  0.71531654,  0.84273568,  0.51857181],
       [-0.66601895, -0.3709413 , -2.17966666,  1.17710721],
       [-0.43184667,  0.24308224,  0.65241893,  0.0124309 ]])

In [145]:
data_copy[:, :] = 0

In [146]:
data_copy

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [147]:
data

array([[-0.5188232 ,  1.68205242, -0.91390822,  1.01310711],
       [-1.08737148,  1.56957886, -0.97882537,  1.1048224 ],
       [-0.59500475,  0.71531654,  0.84273568,  0.51857181],
       [-0.66601895, -0.3709413 , -2.17966666,  1.17710721],
       [-0.43184667,  0.24308224,  0.65241893,  0.0124309 ],
       [ 1.93979481,  2.15641302, -0.18164607,  0.95050426],
       [-1.56534225,  1.39883095,  0.26600091,  1.95348492]])

In [148]:
# Setting values with boolean arrays works in a common-sense way.
data[data < 0] = 0  

In [149]:
data

array([[ 0.        ,  1.68205242,  0.        ,  1.01310711],
       [ 0.        ,  1.56957886,  0.        ,  1.1048224 ],
       [ 0.        ,  0.71531654,  0.84273568,  0.51857181],
       [ 0.        ,  0.        ,  0.        ,  1.17710721],
       [ 0.        ,  0.24308224,  0.65241893,  0.0124309 ],
       [ 1.93979481,  2.15641302,  0.        ,  0.95050426],
       [ 0.        ,  1.39883095,  0.26600091,  1.95348492]])

In [150]:
data[names != 'Joe'] = 7

In [151]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  1.56957886,  0.        ,  1.1048224 ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 1.93979481,  2.15641302,  0.        ,  0.95050426],
       [ 0.        ,  1.39883095,  0.26600091,  1.95348492]])

<h3>Fancy Indexing</h3>

In [152]:
arr = np.empty((8, 4))

In [153]:
for i in range(8):
    arr[i] = i

In [154]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [156]:
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [159]:
arr[2, 2]

2.0

In [160]:
arr[[-3, -5, -7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [161]:
arr = np.arange(32).reshape((8,4))

In [162]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [163]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [164]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [165]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [166]:
# Keep in mind that fancy indexing, unlike slicing, 
# always copies the data into a new array.

<h3> Transposing Arrays and Swapping Axes </h3>

In [167]:
arr = np.arange(15).reshape((3, 5))

In [168]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [169]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [170]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [171]:
arr = np.random.randn(6, 3)

In [172]:
np.dot(arr.T, arr)

array([[ 6.16456551, -1.26862683,  0.60873721],
       [-1.26862683,  3.90653421, -0.4889176 ],
       [ 0.60873721, -0.4889176 ,  5.75306944]])

In [173]:
arr = np.arange(16).reshape((2, 2, 4))

In [174]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [175]:
arr.transpose((1, 0, 2)) # swap axis 1 and axis 0

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [176]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [177]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [178]:
# swapaxes similarly returns a view on the data without making a copy.

<h2>Universal Functions: Fast Element-wise Array Functions</h2>

In [179]:
arr = np.arange(10)

In [180]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [181]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [182]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [183]:
x = np.random.randn(8)

In [184]:
y = np.random.randn(8)

In [185]:
x

array([-0.78173002,  0.29852214,  0.47598844,  0.23059492,  2.17021594,
        1.15660119,  0.55461955,  0.29004264])

In [186]:
y

array([-1.08798516,  0.77461728,  0.34684775,  2.24212501,  0.3511509 ,
        0.322674  , -0.95341685, -1.66468293])

In [187]:
np.maximum(x, y) # element-wise maximum

array([-0.78173002,  0.77461728,  0.47598844,  2.24212501,  2.17021594,
        1.15660119,  0.55461955,  0.29004264])

In [188]:
arr = np.random.randn(7) * 5

In [189]:
np.modf(arr)

(array([ 0.50915434,  0.83165964, -0.65065539,  0.24090364, -0.15424807,
        -0.15956743, -0.04286754]), array([ 0.,  4., -1.,  1., -1., -6., -5.]))

In [190]:
arr

array([ 0.50915434,  4.83165964, -1.65065539,  1.24090364, -1.15424807,
       -6.15956743, -5.04286754])

<h2>Data Processing Using Arrays</h2>